arrowParens: avoid
bracketSpacing: true
endOfLine: lf
insertPragma: false
jsxBracketSameLine: false
jsxSingleQuote: true
printWidth: 120
quoteProps: as-needed
semi: false
singleQuote: true
tabWidth: 2
trailingComma: none

